import type { Metadata } from "next";
import { Fascinate, Lora } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/Navigation";

const fascinateFont = Fascinate({
  variable: "--font-fascinate",
  subsets: ["latin"],
  weight: "400",
});

const loraFont = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fascinateFont.variable} ${loraFont.variable}`}>
        <main className="min-h-screen">
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
